SELECT half.FLAVOR
FROM FIRST_HALF as half JOIN ICECREAM_INFO as info ON half.FLAVOR = info.FLAVOR
WHERE half.TOTAL_ORDER > 3000 and info.INGREDIENT_TYPE = 'fruit_based'
ORDER BY half.TOTAL_ORDER DESC
